/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
/*this project is blinking led on the port no 13 of GPIOA
 but with defining the interface by struct union method */

#include "stdint.h"

typedef volatile unsigned int Vuint32_t;
//defining the GPIOA base address
# define GPIOA_Base 0x40010800
#define  RCC_Base   0X40021000
#define RCC_APB2ENR *(Vuint32_t*)(RCC_Base + 0x18)
#define IOPAEN (1<<2)
typedef struct{
	Vuint32_t CRL;
	union {
		Vuint32_t CRH;
		struct{
			Vuint32_t reserved : 20;
	        Vuint32_t PinA_Mode :4;
		}mode;
	}CRH;
	Vuint32_t IDR;
	union {
		Vuint32_t ODR;
		struct{
		 Vuint32_t reserved :13;
		 Vuint32_t PIN_13 : 1;
		}pin;
	}ODR;
	Vuint32_t BSRR;
	Vuint32_t BRR;
	Vuint32_t LCKR;

} R_GPIOA_t;

volatile R_GPIOA_t *R_ODR = (volatile R_GPIOA_t*) (GPIOA_Base);

int main() {

	RCC_APB2ENR |= IOPAEN ;
	R_ODR->CRH.mode.PinA_Mode = 0 ;
	R_ODR->CRH.mode.PinA_Mode = 2 ;

	volatile int i = 0 ;
	while(1)
	{
		R_ODR->ODR.pin.PIN_13 =1 ;
		for (i = 0 ; i <10000 ; i ++);
		R_ODR->ODR.pin.PIN_13 =0 ;
			for (i = 0 ; i <10000 ; i ++);


	}
	return 0 ;


}
